/*
	SlimeVR Code is placed under the MIT license
	Copyright (c) 2025 SlimeVR Contributors

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.
*/
#include "globals.h"
#include "esb.h"

uint16_t led_clock = 0;

// RFT: provided by esb.c — sync_thread gates on these.
extern bool esb_initialized;
extern bool esb_paired;

LOG_MODULE_REGISTER(timer, 4);

// RFT: SyncTX rewrite #2.
//
// Why the previous PRX↔PTX swap approach was broken:
//   ESB trackers run in PTX mode permanently. A PTX-mode device can only
//   receive *ACK payloads* — replies to its own TX, generated by the PRX
//   peer. Unsolicited PTX broadcasts from a "PRX who briefly switches to
//   PTX" are not received because both sides are then transmitting (or
//   the tracker is in its short ACK-listen window which doesn't coincide
//   with our broadcast).
//
//   Upstream slimevr-receiver's timer.c does the same swap dance, but
//   IRQ_DIRECT_CONNECT was commented out and timer_init() was never
//   called — meaning their sync never actually fired in the public build.
//
// Correct approach (this file):
//   Keep the radio in PRX permanently. Call esb_write_sync() periodically;
//   esb_write_payload() in PRX mode queues the data into the ACK payload
//   FIFO. The next time a tracker transmits, the ESB hardware auto-attaches
//   that payload to its ACK frame, and the tracker receives it via
//   ESB_EVENT_RX_RECEIVED.
//
//   Refresh rate is just a balance between latency and FIFO churn. 50 Hz
//   gives <20 ms command latency once a tracker is sending data.
static void sync_thread(void)
{
	// Wait for the system to stabilise (USB CDC, ESB pairing) before we
	// start poking the radio.
	k_msleep(2000);
	while (1) {
		k_msleep(20);  // 50 Hz refresh of the ACK payload
		if (!esb_initialized || !esb_paired) continue;
		// Stays in PRX. esb_write_payload is dispatched as ACK payload by
		// the ESB driver since we're configured as PRX.
		esb_write_sync(led_clock);
		led_clock++;
		led_clock %= 17 * 600 / 3;
	}
}
K_THREAD_DEFINE(sync_thread_id, 1024, sync_thread, NULL, NULL, NULL, 5, 0, 0);

// Kept as a no-op so esb_thread's call site doesn't need conditional code.
void timer_init(void) { }
